// AUTO-GENERATED by `bun run optimize:photos` (scripts/optimize-photos.ts).
// Do not edit by hand — your changes will be overwritten. Edit `app/life/photos.ts` instead.

export type LifePhoto = {
    /** Path prefix of the optimized files, e.g. "/life/uber-first-day". */
    base: string;
    /** Widths (px) actually generated, ascending, e.g. [640, 1024, 1680]. */
    widths: number[];
    /** Intrinsic width of the largest generated file. */
    width: number;
    /** Intrinsic height of the largest generated file (4:3 of width). */
    height: number;
    /** Tiny base64 data URL used as a blurred placeholder. */
    blurDataURL: string;
    tags: string[];
    description: string;
    alt: string;
};

export const photos: LifePhoto[] = [];
