/**
 * Optimizes the /life gallery photos.
 *
 * Reads the curated list in `app/life/photos.ts`, and for each entry:
 *   - resizes the original from `photos/originals/<file>` to a set of widths,
 *   - crops to a 4:3 landscape box (object-cover semantics),
 *   - encodes each width as WebP into `public/life/`,
 *   - generates a tiny base64 blur placeholder,
 *   - records intrinsic dimensions.
 *
 * Then writes `app/life/photos.generated.ts` (the manifest the page renders).
 *
 * Run with: bun run optimize:photos
 * Only optimized WebP files (small) + the manifest get committed. Originals stay git-ignored.
 */
import { existsSync } from 'node:fs';
import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import sharp from 'sharp';

import { photos as inputs, type PhotoInput } from '../app/life/photos.ts';

const ROOT = path.resolve(import.meta.dirname, '..');
const ORIGINALS_DIR = path.join(ROOT, 'photos', 'originals');
const OUTPUT_DIR = path.join(ROOT, 'public', 'life');
const MANIFEST_PATH = path.join(ROOT, 'app', 'life', 'photos.generated.ts');

// Cells are ~400px wide on desktop (body is max-w-[840px], 2 cols) and full-width on mobile.
// 640 covers desktop @1x/@2x; 1024/1680 cover retina + full-width tablet. We never upscale.
const TARGET_WIDTHS = [640, 1024, 1680];
const ASPECT = 3 / 4; // height / width (4:3 landscape)
const WEBP_QUALITY = 80;
const BLUR_WIDTH = 16;

type GeneratedPhoto = {
    base: string;
    widths: number[];
    width: number;
    height: number;
    blurDataURL: string;
    tags: string[];
    description: string;
    alt: string;
};

/** Turn "uber-first-day.jpg" into "uber-first-day". */
function slugOf(file: string): string {
    return file.replace(/\.[^.]+$/, '');
}

async function blurPlaceholder(image: sharp.Sharp): Promise<string> {
    const buf = await image
        .clone()
        .resize(BLUR_WIDTH, Math.round(BLUR_WIDTH * ASPECT), { fit: 'cover' })
        .webp({ quality: 40 })
        .toBuffer();
    return `data:image/webp;base64,${buf.toString('base64')}`;
}

async function processPhoto(input: PhotoInput): Promise<GeneratedPhoto> {
    const slug = slugOf(input.file);
    const originalPath = path.join(ORIGINALS_DIR, input.file);

    if (!existsSync(originalPath)) {
        throw new Error(
            `Missing original: ${path.relative(ROOT, originalPath)} (referenced by app/life/photos.ts)`,
        );
    }

    const original = sharp(originalPath).rotate(); // rotate() honors EXIF orientation
    const meta = await original.metadata();
    const sourceWidth = meta.width ?? Math.max(...TARGET_WIDTHS);

    // Never upscale: only emit widths the source can actually fill. Always keep the smallest.
    let widths = TARGET_WIDTHS.filter((w) => w <= sourceWidth);
    if (widths.length === 0) widths = [Math.min(...TARGET_WIDTHS)];

    for (const w of widths) {
        const h = Math.round(w * ASPECT);
        const outPath = path.join(OUTPUT_DIR, `${slug}-${w}.webp`);
        await original
            .clone()
            .resize(w, h, { fit: 'cover', position: 'attention' })
            .webp({ quality: WEBP_QUALITY })
            .toFile(outPath);
    }

    const maxWidth = Math.max(...widths);
    const blurDataURL = await blurPlaceholder(original);

    return {
        base: `/life/${slug}`,
        widths,
        width: maxWidth,
        height: Math.round(maxWidth * ASPECT),
        blurDataURL,
        tags: input.tags,
        description: input.description,
        alt: input.alt ?? input.description,
    };
}

function renderManifest(photos: GeneratedPhoto[]): string {
    const header = `// AUTO-GENERATED by \`bun run optimize:photos\` (scripts/optimize-photos.ts).
// Do not edit by hand — your changes will be overwritten. Edit \`app/life/photos.ts\` instead.

export type LifePhoto = {
    /** Path prefix of the optimized files, e.g. "/life/uber-first-day". */
    base: string;
    /** Widths (px) actually generated, ascending, e.g. [640, 1024, 1680]. */
    widths: number[];
    /** Intrinsic width of the largest generated file. */
    width: number;
    /** Intrinsic height of the largest generated file (4:3 of width). */
    height: number;
    /** Tiny base64 data URL used as a blurred placeholder. */
    blurDataURL: string;
    tags: string[];
    description: string;
    alt: string;
};

export const photos: LifePhoto[] = `;

    return `${header}${JSON.stringify(photos, null, 4)};\n`;
}

async function main() {
    await mkdir(ORIGINALS_DIR, { recursive: true });
    await mkdir(OUTPUT_DIR, { recursive: true });

    if (inputs.length === 0) {
        console.log(
            'No photos listed in app/life/photos.ts — writing empty manifest.',
        );
    }

    const generated: GeneratedPhoto[] = [];
    for (const input of inputs) {
        process.stdout.write(`Optimizing ${input.file} … `);
        const photo = await processPhoto(input);
        generated.push(photo);
        console.log(`done (${photo.widths.join('/')}w)`);
    }

    await writeFile(MANIFEST_PATH, renderManifest(generated), 'utf8');
    console.log(
        `\nWrote ${generated.length} photo(s) to app/life/photos.generated.ts and public/life/.`,
    );
}

main().catch((err) => {
    console.error(`\noptimize:photos failed: ${err.message}`);
    process.exit(1);
});
