import sharp from 'sharp';

// Cells are ~400px wide on desktop (body is max-w-[840px], 2 cols) and full-width on mobile.
// 640 covers desktop @1x/@2x; 1024/1680 cover retina + full-width tablet. We never upscale.
export const TARGET_WIDTHS = [640, 1024, 1680];
export const ASPECT = 3 / 4; // height / width (4:3 landscape)
export const WEBP_QUALITY = 80;
export const BLUR_WIDTH = 16;

export type GeneratedPhoto = {
    base: string;
    widths: number[];
    width: number;
    height: number;
    blurDataURL: string;
    tags: string[];
    description: string;
    alt: string;
};

export type OptimizedVariant = { width: number; data: Buffer };

export type OptimizedImage = {
    widths: number[];
    width: number;
    height: number;
    blurDataURL: string;
    files: OptimizedVariant[];
};

/** Turn "uber-first-day.jpg" into "uber-first-day". */
export function slugOf(file: string): string {
    return file.replace(/\.[^.]+$/, '');
}

async function blurPlaceholder(image: sharp.Sharp): Promise<string> {
    const buf = await image
        .clone()
        .resize(BLUR_WIDTH, Math.round(BLUR_WIDTH * ASPECT), { fit: 'cover' })
        .webp({ quality: 40 })
        .toBuffer();
    return `data:image/webp;base64,${buf.toString('base64')}`;
}

/**
 * Resize a source image into the target WebP widths (+ a blur placeholder),
 * returning encoded buffers instead of writing to disk. Crops to a 4:3 landscape
 * box with content-aware positioning; never upscales beyond the source width.
 */
export async function optimizePhoto(buffer: Buffer): Promise<OptimizedImage> {
    const original = sharp(buffer).rotate(); // rotate() honors EXIF orientation
    const meta = await original.metadata();
    const sourceWidth = meta.width ?? Math.max(...TARGET_WIDTHS);

    // Never upscale: only emit widths the source can actually fill. Always keep the smallest.
    let widths = TARGET_WIDTHS.filter((w) => w <= sourceWidth);
    if (widths.length === 0) widths = [Math.min(...TARGET_WIDTHS)];

    const files: OptimizedVariant[] = [];
    for (const w of widths) {
        const h = Math.round(w * ASPECT);
        const data = await original
            .clone()
            .resize(w, h, { fit: 'cover', position: 'attention' })
            .webp({ quality: WEBP_QUALITY })
            .toBuffer();
        files.push({ width: w, data });
    }

    const maxWidth = Math.max(...widths);
    const blurDataURL = await blurPlaceholder(original);

    return {
        widths,
        width: maxWidth,
        height: Math.round(maxWidth * ASPECT),
        blurDataURL,
        files,
    };
}

/** Serialize the render manifest written to `app/life/photos.generated.ts`. */
export function renderManifest(photos: GeneratedPhoto[]): string {
    const header = `// AUTO-GENERATED by \`bun run optimize:photos\` (scripts/optimize-photos.ts) or the
// /admin photo portal. Do not edit by hand — your changes will be overwritten.
// Edit \`app/life/photos.ts\` instead.

export type LifePhoto = {
    /** Path prefix of the optimized files, e.g. "/life/uber-first-day". */
    base: string;
    /** Widths (px) actually generated, ascending, e.g. [640, 1024, 1680]. */
    widths: number[];
    /** Intrinsic width of the largest generated file. */
    width: number;
    /** Intrinsic height of the largest generated file (4:3 of width). */
    height: number;
    /** Tiny base64 data URL used as a blurred placeholder. */
    blurDataURL: string;
    tags: string[];
    description: string;
    alt: string;
};

export const photos: LifePhoto[] = `;

    return `${header}${JSON.stringify(photos, null, 4)};\n`;
}
